apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loghouse
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-realm: "Authrentication Required"
{{- if .Values.https }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
  rules:
  - host: {{ .Values.loghouse_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: loghouse
          servicePort: http
{{- if .Values.https }}
  tls:
  - hosts:
    - {{ .Values.loghouse_host }}
    secretName: loghouse
{{- end }}
