---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: loghouse
  namespace: kube-logging
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: loghouse
    spec:
      containers:
      - name: loghouse
        image: wimbo/loghouse
        imagePullPolicy: Always
        command: ["bundle", "exec", "puma"]
        ports:
        - name: http
          containerPort: 9292
        env:
        - name: CLICKHOUSE_URL
          value: "http://ch.domain/"
        - name: CLICKHOUSE_USERNAME
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          value: ""
        - name: CLICKHOUSE_DATABASE
          value: "logs"
        livenessProbe:
          tcpSocket:
            port: 9292
        readinessProbe:
          tcpSocket:
            port: 9292
        resources:
          requests:
            cpu: "0.2"
          limits:
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: loghouse
  namespace: kube-logging
spec:
  selector:
    component: loghouse
  ports:
    - name: http
      port: 9292
      targetPort: 9292
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loghouse
  namespace: kube-logging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: ch.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: loghouse
          servicePort: 9292
  tls:
  - hosts:
    - ch.domain
    secretName: loghouse
