{{- if not .Values.clickhouse.external }}
kind: ConfigMap
apiVersion: v1
data:
  config.xml: |-
    <?xml version="1.0"?>
    <yandex>
        <logger>
            <level>warning</level>
            <console>1</console>
        </logger>
        <http_port>{{ .Values.clickhouse.httpPort }}</http_port>
        <tcp_port>{{ .Values.clickhouse.port }}</tcp_port>
        <listen_host>0.0.0.0</listen_host>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        <remote_servers incl="clickhouse_remote_servers" />
        <zookeeper incl="zookeeper-servers" optional="true" />
        <macros incl="macros" optional="true" />
        <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
        <max_session_timeout>3600</max_session_timeout>
        <default_session_timeout>60</default_session_timeout>
        <query_log>
            <database>system</database>
            <table>query_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_log>
        <dictionaries_config>*_dictionary.xml</dictionaries_config>
        <compression incl="clickhouse_compression">
        </compression>
        <resharding>
            <task_queue_path>/clickhouse/task_queue</task_queue_path>
        </resharding>
        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
        </distributed_ddl>
    </yandex>
  users.xml: |-
    <?xml version="1.0"?>
    <yandex>
        <profiles>
            <default>
                <max_memory_usage>{{ include "toBytesNotBelow" (dict "limit" .Values.clickhouse.resources.limits.memory "reserve" .Values.clickhouse.resources.reserveMemory) }}</max_memory_usage>
                <max_memory_usage_for_user>{{ include "toBytesNotBelow" (dict "limit" .Values.clickhouse.resources.limits.memory "reserve" .Values.clickhouse.resources.reserveMemory) }}</max_memory_usage_for_user>
                <max_memory_usage_for_all_queries>{{ include "toBytesNotBelow" (dict "limit" .Values.clickhouse.resources.limits.memory "reserve" .Values.clickhouse.resources.reserveMemory) }}</max_memory_usage_for_all_queries>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
            <readonly>
                <readonly>1</readonly>
            </readonly>
        </profiles>
        <users>
            <default>
                <password_sha256_hex>{{ .Values.clickhouse.password | sha256sum }}</password_sha256_hex>
                <networks incl="networks" replace="replace">
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
            </default>
        </users>

        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </yandex>
metadata:
  name: clickhouse-config
  namespace: {{ .Release.Namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
