{{- if .Values.storage.pvc.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    volume.beta.kubernetes.io/mount-options: "discard"
spec:
  accessModes:
    - {{ .Values.storage.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  storageClassName: {{ .Values.storage.pvc.storageClassName }}
{{- end }}
