{{- if (and .Values.ingress.enable .Values.enable_tabix) }}
apiVersion: {{ template "Ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: clickhouse
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if or .Values.ingress.clickhouse.annotations .Values.ingress.clickhouse.ingressClass }}
    kubernetes.io/ingress.class: {{ .Values.ingress.clickhouse.ingressClass | quote }}
{{- range $key, $value := .Values.ingress.clickhouse.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.ingress.enable_https }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.clickhouse.host }}
    http:
      paths:
      - path: {{ .Values.ingress.clickhouse.path }}
        backend:
          serviceName: clickhouse
          servicePort: http
{{- if .Values.ingress.enable_https }}
  tls:
  - hosts:
    - {{ .Values.ingress.clickhouse.host }}
    secretName: {{ .Values.ingress.clickhouse.tls_secret_name}}
{{- if .Values.ingress.clickhouse.tls_issuer }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.ingress.clickhouse.tls_secret_name}}
spec:
  acme:
    config:
    - domains:
      - {{ .Values.ingress.clickhouse.host }}
      http01:
{{- if .Values.ingress.clickhouse.ingressClass }}
        ingressClass: {{ .Values.ingress.clickhouse.ingressClass | quote }}
{{- else }}
        ingressClass: "nginx"
{{- end }}
  dnsNames:
  - {{ .Values.ingress.clickhouse.host }}
  issuerRef:
{{- if .Values.ingress.clickhouse.tls_issuer_kind }}
    kind: {{ .Values.ingress.clickhouse.tls_issuer_kind }}
{{- else }}
    kind: ClusterIssuer
{{- end }}
    name:  {{ .Values.ingress.clickhouse.tls_issuer }}
  secretName: {{ .Values.ingress.clickhouse.tls_secret_name }}
{{- end }}
{{- end }}
{{- end }}
