---
kind: ConfigMap
apiVersion: v1
metadata:
  name: loghouse-nginx-conf
  namespace: {{ .Release.Namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  nginx.conf: |-
    worker_processes auto;
    daemon off;
    error_log /dev/stderr info;
    events {
      worker_connections 1024;
    }

    http {
      access_log /dev/stdout;
      include /etc/nginx/mime.types;
      gzip on;
      gzip_disable "msie6";
      gzip_types text/plain text/css text/xml text/javascript application/javascript application/x-javascript application/xml image/jpeg image/png;

      set_real_ip_from 192.168.0.0/16;
      set_real_ip_from 10.0.0.0/8;
      set_real_ip_from 172.16.0.0/12;

      server {
        server_name _;
        listen 80;

        location / {
          auth_basic "Authrentication Required";
          auth_basic_user_file /nginx/passwd/auth;
          proxy_redirect      off;
          proxy_read_timeout  10m;
          proxy_set_header    Host          $http_host;
          proxy_set_header    X-Real-Ip     $remote_addr;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:9292;
        }
      }
    }
