apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-init-tables
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/weight": "5"
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ .Chart.Name }}-init-tables
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-clickhouse
        image: alpine:3.6
        command: [ '/bin/sh', '-c', 'while ! getent ahostsv4 clickhouse; do sleep 1; done' ]
      containers:
      - name: init-tables
        image: flant/loghouse-dashboard:{{ .Chart.Version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ['/bin/bash', '-l', '-c', 'rake create_logs_tables']
        env:
        - name: KUBERNETES_DEPLOYED
          value: {{ now | quote }}
        - name: CLICKHOUSE_URL
          value: "clickhouse:8123"
        - name: CLICKHOUSE_USERNAME
          value: {{ .Values.clickhouse.user | quote }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.clickhouse_pass_original | quote }}
        - name: CLICKHOUSE_DATABASE
          value: {{ .Values.clickhouse.db | quote }}
        - name: CLICKHOUSE_LOGS_TABLE
          value: {{ .Values.clickhouse.table | quote }}
        - name: LOGS_TABLES_PARTITION_PERIOD
          value: {{ .Values.partition_period | quote }}
        - name: RACK_ENV
          value: "production"
