---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghouse
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: loghouse
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: loghouse
    spec:
      serviceAccountName: loghouse
      initContainers:
      - name: wait-clickhouse
        image: alpine:3.6
        command: [ '/bin/sh', '-c', 'while ! nc -z clickhouse 8123; do sleep 1; done' ]
      containers:
      - name: frontend
        image: nginx:alpine
        command: ["/usr/sbin/nginx"]
        ports:
        - name: http
          containerPort: 80
        env:
        - name: KUBERNETES_DEPLOYED
          value: {{ now | quote }}
        volumeMounts:
        - name: basic-auth
          mountPath: "/nginx/passwd"
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      - name: backend
        image: flant/loghouse-dashboard:{{ template "app.version" $ }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["bundle", "exec", "puma"]
        ports:
        - name: http2
          containerPort: 9292
        env:
        - name: KUBERNETES_DEPLOYED
          value: {{ now | quote }}
        - name: CLICKHOUSE_URL
          value: "clickhouse:8123"
        - name: CLICKHOUSE_DATABASE
          value: {{ .Values.clickhouse.db | quote }}
        - name: CLICKHOUSE_LOGS_TABLE
          value: {{ .Values.clickhouse.table | quote }}
        - name: LOGS_TABLES_PARTITION_PERIOD
          value: {{ .Values.partition_period | quote }}
        - name: PERMISSONS_FILE_PATH
          value: "/config/user.conf"
        - name: RACK_ENV
          value: "production"
        - name: CLICKHOUSE_USERNAME
          valueFrom:
            secretKeyRef:
              name: clickhouse
              key: CLICKHOUSE_USER
        envFrom:
        - secretRef:
            name: clickhouse
        volumeMounts:
        - name: user-config
          mountPath: /config
        livenessProbe:
          tcpSocket:
            port: 9292
        readinessProbe:
          tcpSocket:
            port: 9292
        {{ include "includeByName" (dict "root" .Values.loghouse "name" "resources") | indent 8 | trim }}
      volumes:
      - name: user-config
        configMap:
          name: loghouse-user-config
      - name: basic-auth
        secret:
          secretName: basic-auth
      - name: nginx-conf
        configMap:
          name: loghouse-nginx-conf
      {{ include "includeByName" (dict "root" .Values.clickhouse "name" "nodeSelector") | indent 6 | trim }}
      {{ include "includeByName" (dict "root" .Values.clickhouse "name" "tolerations") | indent 6 | trim }}
