apiVersion: {{ template "CronJob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-tables
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "59 23 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: wait-clickhouse
            image: alpine:3.6
            command: [ '/bin/sh', '-c', 'while ! nc -z clickhouse 8123; do sleep 1; done' ]
          containers:
            - name: cron
              image: flant/loghouse-dashboard:{{ template "app.version" $ }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              command: ['/bin/bash', '-l', '-c', 'rake create_logs_tables']
              env:
              - name: KUBERNETES_DEPLOYED
                value: {{ now | quote }}
              - name: CLICKHOUSE_URL
                value: "clickhouse:8123"
              - name: CLICKHOUSE_USERNAME
                value: {{ .Values.clickhouse.user | quote }}
              - name: CLICKHOUSE_PASSWORD
                value: {{ .Values.clickhouse_pass_original | quote }}
              - name: CLICKHOUSE_DATABASE
                value: {{ .Values.clickhouse.db | quote }}
              - name: LOGS_TABLES_PARTITION_PERIOD
                value: {{ .Values.partition_period | quote }}
              - name: CLICKHOUSE_LOGS_TABLE
                value: {{ .Values.clickhouse.table | quote }}
