apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-init-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/weight": "-5"
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: {{ .Chart.Name }}-init-db
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-clickhouse
        image: alpine:3.6
        command: [ '/bin/sh', '-c', 'while ! nc -z clickhouse 8123; do sleep 1; done' ]
      containers:
      - name: init
        image: flant/loghouse-fluentd:{{ template "app.version" $ }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ['/bin/bash', '-l', '-c', 'clickhouse-client --host=${CLICKHOUSE_URL} --port=9000 --user=${CLICKHOUSE_USERNAME} --password=${CLICKHOUSE_PASSWORD} --query="CREATE DATABASE ${CLICKHOUSE_DATABASE};"']
        env:
        - name: KUBERNETES_DEPLOYED
          value: {{ now | quote }}
        - name: CLICKHOUSE_URL
          value: "clickhouse"
        - name: CLICKHOUSE_USERNAME
          value: {{ .Values.clickhouse.user | quote }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.clickhouse_pass_original | quote }}
        - name: CLICKHOUSE_DATABASE
          value: {{ .Values.clickhouse.db | quote }}
        - name: CLICKHOUSE_LOGS_TABLE
          value: {{ .Values.clickhouse.table | quote }}
        - name: LOGS_TABLES_PARTITION_PERIOD
          value: {{ .Values.partition_period | quote }}
        - name: RACK_ENV
          value: "production"
